[package]
name = "bevy_lunex"
version = "0.1.0"
edition = "2021"


[dependencies]
ahash = "0.8.3"
bevy = { git = "https://github.com/idedary/bevy", default-features = false, features = ["bevy_sprite", "bevy_render", "bevy_text"] }
colored = "2.0.0"
