[package]
name = "bevy_lunex"
version = "0.0.7"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Dominik Kaspar"]
repository = "https://github.com/bytestring-net/bevy-lunex"
keywords = ["ui", "layout", "bevy", "lunex", "bevy-lunex"]
categories = ["gui", "mathematics", "game-development"]
description = "Blazingly fast path based modular layout system built on top of Bevy ECS"
readme = "README.md"

exclude = [
  "promo/*",
]

members = [
  "crates/*",
]

[dependencies]
bevy_lunex_core = { path = "crates/bevy_lunex_core", version = "0.0.7"}
#bevy_lunex_macros = { path = "crates/bevy_lunex_macros", version = "0.0.7"}
bevy_lunex_ui = { path = "crates/bevy_lunex_ui", version = "0.0.7"}
bevy_lunex_utility = { path = "crates/bevy_lunex_utility", version = "0.0.7"}