[workspace]
  resolver = "2"
  members = [
    "crates/*",
    "examples/*",
  ]

[profile.dev]
  opt-level = 1

[workspace.package]
  authors     = ["Dominik Kaspar"]
  version     = "0.0.1"
  edition     = "2021"
  license     = "MIT OR Apache-2.0"
  repository  = "https://github.com/bytestring-net/bevy-lunex"
  keywords    = ["ui", "layout", "bevy", "lunex", "bevy-lunex"]
  categories  = ["gui", "mathematics", "game-development"]

[workspace.dependencies]

  bevy_lunex   = { path = "crates/bevy_lunex" }
  lunex_engine = { path = "crates/lunex_engine" }


  ahash              = { version = "^0.8" }
  colored            = { version = "^2.1" }
  indexmap           = { version = "^2.1" }
  thiserror          = { version = "^1.0" }

  bevy = { version = "0.13.1", default_features = false, features = [
    #"bevy_asset",
    #"bevy_gilrs",
    #"bevy_winit",
    #"bevy_core_pipeline",
    "bevy_pbr",
    #"bevy_render",
    "bevy_sprite",
    "bevy_text",
    "multi-threaded",
    #"png",
    #"hdr",
    #"x11",
    "bevy_gizmos",
    #"default_font",
  ] }

  #bevy_mod_picking   = { version = "0.18.2"}  
  #lunex_engine = { git = "https://github.com/bytestring-net/lunex_engine" }
  #lunex_engine = { path = "/home/dominik/Projects/Bytestring/lunex_engine/crates/lunex_engine", features=["bevy"] }