[package]
name = "bevy_lunex"
version = "0.1.0"
edition = "2021"

members = [
  "crates/*"
]

[dependencies]
bevy_lunex_core = { path = "crates/bevy_lunex_core"}
bevy_lunex_ui = { path = "crates/bevy_lunex_ui"}
bevy_lunex_utility = { path = "crates/bevy_lunex_utility"}
