[package]
name = "lunex_images_example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy_lunex = { path = "../../../../bevy-lunex"}
bevy = { workspace = true, default-features = true, features = ["dynamic_linking"] }
bevy_vector_shapes = { workspace = true }