[package]
name = "lunex_grids_example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy_lunex = { path = "../../../../bevy-lunex"}

bevy = { version = "0.12.0", features = ["dynamic_linking"] }
bevy_vector_shapes = "0.6.0"
